--CREATE SEQUENCE app.EMPLOYEE_SEQ AS INTEGER START WITH 3;
--INSERT INTO app.Tb_EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME,EMPLOYEE_ADRESS, EMPLOYEE_NUMBER,EMPLOYEE_TYPE) values (1, 'Carlos Roberto','SQN 615 BLOCO A','Apto 603','CLT');
--INSERT INTO app.Tb_EMPLOYEE(EMPLOYEE_ID, EMPLOYEE_NAME,EMPLOYEE_ADRESS, EMPLOYEE_NUMBER,EMPLOYEE_TYPE) values (2, 'Luciene Alves Medeiros','SQN 615 BLOCO A','Apto 603','Profissional Liberal');

