--CREATE SCHEMA app;
--CREATE TABLE IF NOT EXISTS app.Tb_EMPLOYEE(EMPLOYEE_ID INTEGER PRIMARY KEY , EMPLOYEE_NAME VARCHAR(255),
--                                                           EMPLOYEE_ADRESS VARCHAR(255),
--                                                           EMPLOYEE_NUMBER VARCHAR(255),
--                                                           EMPLOYEE_TYPE VARCHAR(255));
