server:
  port: 8280

spring:
  application:
    name: Crud-Employee
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


springdoc:
  title: Employees API
  version: 1.0.0


#Banco de Dados
datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:

jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  hibernate:
    ddl-auto: update

h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      web-allow-others: true